#!/bin/bash

docker build \
  --build-arg VERSION=$(git describe --tags --always)  \
  --build-arg COMMIT=$(git rev-parse HEAD) \
  --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  --build-arg VCS_URL=$(git config --get remote.origin.url) \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
-f $DOCKERFILE_PATH \
-t $IMAGE_NAME .
