#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

# TODO: replace with Docker's experimental manifest feature
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

# TODO: unify environment setup in a separate file
REPO=$(echo "$DOCKER_REPO" | cut -d "/" -f 2,3)
HASS_VER=$(echo "$DOCKER_TAG" | cut -d '-' -f 1 | grep '\.')

if [ -n "$HASS_VER" ]; then 
  SED_SAFE_VER=$(echo "$HASS_VER" | sed -e 's/[]\/$*.^[]/\\&/g')
  sed -i "s/\([a-z0-9]\+\)\-latest/$SED_SAFE_VER\-\1/g; s/\:latest/\:$SED_SAFE_VER/g" manifest.yaml
fi

if ./manifest-tool push from-spec manifest.yaml 2> /dev/null; then
  echo "All images pushed successfully, cleaning up tags."
  ${HASS_VER:?Only cleanup SemVer tags} # TODO: Get package version from requirements.txt
  MAJMIN_VER=$(echo "$HASS_VER" | cut -d '.' -f 1,2 -s)
  # Label resulting multi-arch image with additional tags
  echo "tags: [\"${HASS_VER}\", \"${MAJMIN_VER}\", \"latest\"]" >> manifest.yaml
  ./manifest-tool push from-spec manifest.yaml

  ${PA_TOKEN:?PA_TOKEN not configured}
  ${PA_USER:?PA_USER not configured}
  # Obtain JWT for authorization 
  JW_TOKEN=$(curl -s -H "Content-Type: application/json" \
    -X POST -d "{\"username\": \"$PA_USER\", \"password\": \"$PA_TOKEN\"}" \
    https://hub.docker.com/v2/users/login/ | python -c "import sys, json; print json.load(sys.stdin)['token']")
  # Clean up SEMVER-ARCH tags
  for i in "amd64" "arm64" "armhf"; do
    curl -s -H "Authorization: JWT ${JW_TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${REPO}/tags/${HASS_VER}-${i}/"
  done
else
  echo "Manifest images not complete, continuing."
  ./manifest-tool push from-spec --ignore-missing manifest.yaml
fi
