#!/bin/bash -xe

. ./hooks/env
cp Dockerfile.template "${DOCKERFILE_PATH}"
if [ "${BUILD_ARCH}" == 'amd64' ]; then
  sed -i "/__CROSS_/d" "${DOCKERFILE_PATH}"
  echo "qemu-user-static: Download not required for current arch"
  exit 0
else
  sed -i "s/__CROSS_//g" "${DOCKERFILE_PATH}"
fi

curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz" \
    | tar xzv
