#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

HASS_VER=$(echo "$DOCKER_TAG" | cut -d '-' -f 1 | grep '\.')

if [ ! -z "$HASS_VER" ]; then 
  MAJMIN_VER=$(echo "$HASS_VER" | cut -d '.' -f 1,2 -s)
  TAGS=$(echo ", \"${MAJMIN_VER}\", \"${HASS_VER}\"" | sed -e 's/[]\/$*.^[]/\\&/g')
  HASS_VER=$(echo "$HASS_VER" | sed -e 's/[]\/$*.^[]/\\&/g')
  sed -i "s/\([a-z0-9]\+\)\-latest/$HASS_VER\-\1/g; s/\(\"latest\"\)/\1$TAGS/g; s/\:latest/\:$HASS_VER/g" manifest.yaml
fi

./manifest-tool push from-spec --ignore-missing manifest.yaml
