#!/bin/bash -xe

. ./hooks/env

TAG_PREFIX=${DOCKER_TAG%-*}
IMAGE_PREFIX="${IMAGE_NAME%-*}"
IMAGE_LIST=""
for i in "amd64" "arm64" "armhf"; do
  IMAGE_LIST="${IMAGE_LIST}${IMAGE_PREFIX}-${i} "
done

# Enable CLI experimental manifest features
export DOCKER_CLI_EXPERIMENTAL="enabled"

if [ $(docker manifest inspect "${IMAGE_PREFIX}" | grep -i "architecture" | wc -l) -eq 3 ]; then
  echo "All images pushed successfully, cleaning up tags."
  if [ "${TAG_PREFIX}" != "latest" ]; then
    docker manifest create --amend "${IMAGE_PREFIX}" ${IMAGE_LIST}
    docker manifest create --amend "${IMAGE_PREFIX%.*}" ${IMAGE_LIST}
  fi
  docker manifest create --amend "${DOCKER_REPO}:latest" ${IMAGE_LIST} || exit 1

  ${PA_TOKEN:?PA_TOKEN not configured}
  ${PA_USER:?PA_USER not configured}
  # Obtain JWT for authorization 
  JW_TOKEN=$(curl -s -H "Content-Type: application/json" \
    -X POST -d "{\"username\": \"$PA_USER\", \"password\": \"$PA_TOKEN\"}" \
    https://hub.docker.com/v2/users/login/ | python -c "import sys, json; print json.load(sys.stdin)['token']")
  # Clean up SEMVER-ARCH tags
  for i in "amd64" "arm64" "armhf"; do
    curl -s -H "Authorization: JWT ${JW_TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${REPO}/tags/${TAG_PREFIX}-${i}/"
  done
else
  echo "Manifest images not complete, continuing."
  if [[ ${BASEIMAGE_ARCH} == "arm"* ]]; then
    docker manifest annotate ${IMAGE_PREFIX} ${IMAGE_NAME} --os linux --arch "${DOCKER_ARCH}" --variant "${BASEIMAGE_ARCH#arm*v}"
  else
    docker manifest annotate ${IMAGE_PREFIX} ${IMAGE_NAME} --os linux --arch "${DOCKER_ARCH}"
  fi
  docker push ${IMAGE_NAME}
fi
